/** Account + API-key templates (transactional security/account notices). */
import { APP_URL } from "../config";
import { greeting, greetingDe, row, strong, type TemplateDef } from "./types";

export const ACCOUNT_TEMPLATES: TemplateDef[] = [
  {
    id: "account-profile-updated",
    name: "Profile updated",
    description: "Confirm profile changes.",
    category: "account",
    kind: "transactional",
    sender: "accounts",
    subject: { en: "Your Verxa profile was updated", de: "Dein Verxa-Profil wurde aktualisiert" },
    preheader: { en: "Changes were saved to your profile.", de: "Änderungen wurden gespeichert." },
    body: {
      en: (v) => [
        { type: "h", text: "Profile updated" },
        { type: "p", text: `${greeting(v)} changes were saved to your Verxa profile${v.note ? `: ${strong(v.note)}` : "."}` },
        { type: "p", text: "Wasn't you? Let us know right away." },
      ],
      de: (v) => [
        { type: "h", text: "Profil aktualisiert" },
        { type: "p", text: `${greetingDe(v)} Änderungen wurden gespeichert${v.note ? `: ${strong(v.note)}` : "."}` },
        { type: "p", text: "Warst du das nicht? Melde dich sofort." },
      ],
    },
    vars: ["name", "email", "note"],
  },
  {
    id: "account-username-changed",
    name: "Username changed",
    description: "Old → new username notice.",
    category: "account",
    kind: "transactional",
    sender: "accounts",
    subject: { en: "Your Verxa username was changed", de: "Dein Verxa-Benutzername wurde geändert" },
    preheader: { en: "Your username was updated.", de: "Dein Benutzername wurde aktualisiert." },
    body: {
      en: (v) => [
        { type: "h", text: "Username changed" },
        { type: "meta", rows: [row("Old username", v.oldUsername), row("New username", v.newUsername)] },
        { type: "p", text: "Wasn't you? Contact support immediately." },
      ],
      de: (v) => [
        { type: "h", text: "Benutzername geändert" },
        { type: "meta", rows: [row("Alter Name", v.oldUsername), row("Neuer Name", v.newUsername)] },
        { type: "p", text: "Warst du das nicht? Kontaktiere sofort den Support." },
      ],
    },
    vars: ["name", "email", "oldUsername", "newUsername"],
  },
  {
    id: "account-email-changed",
    name: "Email changed (account record)",
    description: "Account-record email change notice.",
    category: "account",
    kind: "transactional",
    sender: "accounts",
    subject: { en: "Email on your Verxa account changed", de: "E-Mail deines Verxa-Kontos geändert" },
    preheader: { en: "Your account email is now different.", de: "Deine Konto-E-Mail ist jetzt anders." },
    body: {
      en: (v) => [
        { type: "h", text: "Email changed" },
        { type: "p", text: `${greeting(v)} the email on your Verxa account is now ${strong(v.newEmail)}.` },
      ],
      de: (v) => [
        { type: "h", text: "E-Mail geändert" },
        { type: "p", text: `${greetingDe(v)} die E-Mail deines Kontos lautet jetzt ${strong(v.newEmail)}.` },
      ],
    },
    vars: ["name", "email", "newEmail"],
  },
  {
    id: "account-security-settings-changed",
    name: "Security settings changed",
    description: "Any security setting update.",
    category: "security",
    kind: "transactional",
    sender: "security",
    subject: { en: "Your security settings were changed", de: "Deine Sicherheitseinstellungen wurden geändert" },
    preheader: { en: "Review this change to stay safe.", de: "Prüfe diese Änderung." },
    body: {
      en: (v) => [
        { type: "h", text: "Security settings updated" },
        { type: "p", text: `${greeting(v)} your security settings were changed${v.note ? `: ${strong(v.note)}` : "."}` },
        { type: "btn", label: "Review security", href: `${APP_URL}/account/security` },
        { type: "note", text: "If this wasn't you, reset your password immediately." },
      ],
      de: (v) => [
        { type: "h", text: "Sicherheitseinstellungen aktualisiert" },
        { type: "p", text: `${greetingDe(v)} deine Einstellungen wurden geändert${v.note ? `: ${strong(v.note)}` : "."}` },
        { type: "btn", label: "Sicherheit prüfen", href: `${APP_URL}/account/security` },
        { type: "note", text: "Wenn du das nicht warst, setze dein Passwort sofort zurück." },
      ],
    },
    vars: ["name", "email", "note", "timestamp"],
  },
  {
    id: "account-2fa-enabled",
    name: "Two-factor authentication enabled",
    description: "2FA turned on.",
    category: "security",
    kind: "transactional",
    sender: "security",
    subject: { en: "Two-factor authentication is now on", de: "Zwei-Faktor-Auth ist jetzt aktiv" },
    preheader: { en: "Your account just got safer.", de: "Dein Konto ist jetzt sicherer." },
    body: {
      en: (v) => [
        { type: "h", text: "2FA enabled ✓" },
        { type: "p", text: `${greeting(v)} two-factor authentication is now protecting your Verxa account.` },
        { type: "p", text: "Keep your recovery codes somewhere safe — they're the only way back in if you lose your device." },
      ],
      de: (v) => [
        { type: "h", text: "2FA aktiviert ✓" },
        { type: "p", text: `${greetingDe(v)} die Zwei-Faktor-Authentifizierung schützt jetzt dein Konto.` },
        { type: "p", text: "Bewahre deine Wiederherstellungscodes sicher auf — sie sind der einzige Weg zurück bei Geräteverlust." },
      ],
    },
    vars: ["name", "email", "timestamp"],
  },
  {
    id: "account-2fa-disabled",
    name: "Two-factor authentication disabled",
    description: "2FA turned off — high attention.",
    category: "security",
    kind: "transactional",
    sender: "security",
    subject: { en: "⚠ Two-factor authentication was turned off", de: "⚠ Zwei-Faktor-Auth wurde deaktiviert" },
    preheader: { en: "Your account is less protected now.", de: "Dein Konto ist jetzt schlechter geschützt." },
    body: {
      en: (v) => [
        { type: "h", text: "2FA disabled" },
        { type: "p", text: `${greeting(v)} two-factor authentication was turned off on your account.` },
        { type: "note", text: "If this wasn't you, re-enable 2FA and reset your password immediately." },
        { type: "btn", label: "Review security", href: `${APP_URL}/account/security` },
      ],
      de: (v) => [
        { type: "h", text: "2FA deaktiviert" },
        { type: "p", text: `${greetingDe(v)} die Zwei-Faktor-Authentifizierung wurde deaktiviert.` },
        { type: "note", text: "Wenn du das nicht warst, aktiviere 2FA erneut und setze dein Passwort sofort zurück." },
        { type: "btn", label: "Sicherheit prüfen", href: `${APP_URL}/account/security` },
      ],
    },
    vars: ["name", "email", "timestamp"],
  },
  {
    id: "account-new-device",
    name: "New device detected",
    description: "First activity from an unknown device.",
    category: "security",
    kind: "transactional",
    sender: "security",
    subject: { en: "New device on your Verxa account", de: "Neues Gerät bei deinem Verxa-Konto" },
    preheader: { en: "We haven't seen this device before.", de: "Dieses Gerät kennen wir noch nicht." },
    body: {
      en: (v) => [
        { type: "h", text: "New device" },
        { type: "p", text: `${greeting(v)} your account was accessed from a device we haven't seen before.` },
        { type: "meta", rows: [row("Device", v.device), row("Location", v.ipLocation), row("When", v.timestamp)] },
        { type: "note", text: "Recognize it? No action needed. Otherwise reset your password now." },
      ],
      de: (v) => [
        { type: "h", text: "Neues Gerät" },
        { type: "p", text: `${greetingDe(v)} dein Konto wurde von einem unbekannten Gerät aus aufgerufen.` },
        { type: "meta", rows: [row("Gerät", v.device), row("Standort", v.ipLocation), row("Wann", v.timestamp)] },
        { type: "note", text: "Kennst du es? Dann ist nichts zu tun. Sonst setze jetzt dein Passwort zurück." },
      ],
    },
    vars: ["name", "email", "device", "ipLocation", "timestamp"],
  },
  {
    id: "account-new-session",
    name: "New session detected",
    description: "New session started.",
    category: "security",
    kind: "transactional",
    sender: "security",
    subject: { en: "New session started on Verxa", de: "Neue Sitzung bei Verxa gestartet" },
    preheader: { en: "Session details inside.", de: "Details zur Sitzung." },
    body: {
      en: (v) => [
        { type: "h", text: "New session" },
        { type: "p", text: `${greeting(v)} a new session was started on your account.` },
        { type: "meta", rows: [row("Device", v.device), row("When", v.timestamp)] },
        { type: "btn", label: "Manage sessions", href: `${APP_URL}/account/security` },
      ],
      de: (v) => [
        { type: "h", text: "Neue Sitzung" },
        { type: "p", text: `${greetingDe(v)} eine neue Sitzung wurde gestartet.` },
        { type: "meta", rows: [row("Gerät", v.device), row("Wann", v.timestamp)] },
        { type: "btn", label: "Sitzungen verwalten", href: `${APP_URL}/account/security` },
      ],
    },
    vars: ["name", "email", "device", "timestamp"],
  },
  {
    id: "account-session-revoked",
    name: "Session revoked",
    description: "A session was signed out remotely.",
    category: "security",
    kind: "transactional",
    sender: "security",
    subject: { en: "A session was signed out", de: "Eine Sitzung wurde abgemeldet" },
    preheader: { en: "One of your sessions ended.", de: "Eine deiner Sitzungen wurde beendet." },
    body: {
      en: (v) => [
        { type: "h", text: "Session revoked" },
        { type: "p", text: `${greeting(v)} a session on ${strong(v.device ?? "one of your devices")} was signed out.` },
        { type: "p", text: "If you did this, everything is fine. Otherwise review your security settings." },
      ],
      de: (v) => [
        { type: "h", text: "Sitzung beendet" },
        { type: "p", text: `${greetingDe(v)} eine Sitzung auf ${strong(v.device ?? "einem deiner Geräte")} wurde abgemeldet.` },
        { type: "p", text: "Warst du das, ist alles gut. Sonst prüfe deine Sicherheitseinstellungen." },
      ],
    },
    vars: ["name", "email", "device", "timestamp"],
  },
  {
    id: "account-api-key-created",
    name: "API key created",
    description: "A new API key was issued.",
    category: "security",
    kind: "transactional",
    sender: "security",
    subject: { en: "New Verxa API key created", de: "Neuer Verxa-API-Key erstellt" },
    preheader: { en: "Keep the secret safe — it was shown only once.", de: "Geheim halten — wurde nur einmal angezeigt." },
    body: {
      en: (v) => [
        { type: "h", text: "API key created" },
        { type: "p", text: `${greeting(v)} a new API key was created on your account.` },
        { type: "meta", rows: [row("Key name", v.keyName), row("Prefix", v.keyPrefix), row("When", v.timestamp)] },
        { type: "note", text: "The full secret was shown only once. If this wasn't you, revoke the key immediately in your API settings." },
        { type: "btn", label: "Manage API keys", href: `${APP_URL}/api-keys` },
      ],
      de: (v) => [
        { type: "h", text: "API-Key erstellt" },
        { type: "p", text: `${greetingDe(v)} ein neuer API-Key wurde erstellt.` },
        { type: "meta", rows: [row("Name", v.keyName), row("Präfix", v.keyPrefix), row("Wann", v.timestamp)] },
        { type: "note", text: "Das Secret wurde nur einmal angezeigt. Warst du das nicht, widerrufe den Key sofort." },
        { type: "btn", label: "API-Keys verwalten", href: `${APP_URL}/api-keys` },
      ],
    },
    vars: ["name", "email", "keyName", "keyPrefix", "timestamp"],
  },
  {
    id: "account-api-key-revoked",
    name: "API key revoked",
    description: "A key was revoked or deleted.",
    category: "security",
    kind: "transactional",
    sender: "security",
    subject: { en: "A Verxa API key was revoked", de: "Ein Verxa-API-Key wurde widerrufen" },
    preheader: { en: "The key stopped working immediately.", de: "Der Key funktioniert ab sofort nicht mehr." },
    body: {
      en: (v) => [
        { type: "h", text: "API key revoked" },
        { type: "p", text: `${greeting(v)} the API key ${strong(v.keyPrefix ?? "")} (${strong(v.keyName ?? "")}) was revoked and stopped working immediately.` },
      ],
      de: (v) => [
        { type: "h", text: "API-Key widerrufen" },
        { type: "p", text: `${greetingDe(v)} der Key ${strong(v.keyPrefix ?? "")} (${strong(v.keyName ?? "")}) wurde widerrufen und ist sofort ungültig.` },
      ],
    },
    vars: ["name", "email", "keyName", "keyPrefix", "timestamp"],
  },
  {
    id: "account-api-key-expiring",
    name: "API key expiring",
    description: "Reminder before a key expires.",
    category: "account",
    kind: "transactional",
    sender: "notifications",
    subject: { en: "Your API key expires soon", de: "Dein API-Key läuft bald ab" },
    preheader: { en: "Rotate it in time to avoid downtime.", de: "Rechtzeitig rotieren, um Ausfälle zu vermeiden." },
    body: {
      en: (v) => [
        { type: "h", text: "Key expiring soon" },
        { type: "p", text: `${greeting(v)} your API key ${strong(v.keyPrefix ?? "")} expires on ${strong(v.expiresAt ?? "")}. Rotate it in time to avoid downtime.` },
        { type: "btn", label: "Manage API keys", href: `${APP_URL}/api-keys` },
      ],
      de: (v) => [
        { type: "h", text: "Key läuft bald ab" },
        { type: "p", text: `${greetingDe(v)} dein Key ${strong(v.keyPrefix ?? "")} läuft am ${strong(v.expiresAt ?? "")} ab. Rotiere ihn rechtzeitig.` },
        { type: "btn", label: "API-Keys verwalten", href: `${APP_URL}/api-keys` },
      ],
    },
    vars: ["name", "email", "keyName", "keyPrefix", "expiresAt"],
  },
  {
    id: "account-api-usage-warning",
    name: "API usage warning",
    description: "Unusual or high API usage.",
    category: "account",
    kind: "transactional",
    sender: "notifications",
    subject: { en: "Unusual API usage on your account", de: "Ungewöhnliche API-Nutzung" },
    preheader: { en: "Your key usage spiked recently.", de: "Deine Key-Nutzung ist stark gestiegen." },
    body: {
      en: (v) => [
        { type: "h", text: "Usage warning" },
        { type: "p", text: `${greeting(v)} we noticed unusually high usage on key ${strong(v.keyPrefix ?? "")}.` },
        { type: "meta", rows: [row("Requests today", v.amount), row("When", v.timestamp)] },
        { type: "note", text: "If you don't recognize this traffic, revoke the key and create a new one." },
      ],
      de: (v) => [
        { type: "h", text: "Nutzungswarnung" },
        { type: "p", text: `${greetingDe(v)} ungewöhnlich hohe Nutzung auf Key ${strong(v.keyPrefix ?? "")}.` },
        { type: "meta", rows: [row("Anfragen heute", v.amount), row("Wann", v.timestamp)] },
        { type: "note", text: "Unbekannter Traffic? Widerrufe den Key und erstelle einen neuen." },
      ],
    },
    vars: ["name", "email", "keyName", "keyPrefix", "amount", "timestamp"],
  },
];
