/** Billing + plan lifecycle templates (all transactional). */
import { APP_URL } from "../config";
import { greeting, row, strong, type TemplateDef } from "./types";

const subBtn = { type: "btn" as const, label: "Subscription settings", href: `${APP_URL}/account/subscription` };

export const BILLING_TEMPLATES: TemplateDef[] = [
  {
    id: "billing-subscription-started",
    name: "Subscription started",
    description: "Pro plan activated.",
    category: "billing",
    kind: "transactional",
    sender: "billing",
    subject: { en: "Welcome to Verxa Pro", de: "Willkommen bei Verxa Pro" },
    preheader: { en: "Your subscription is active.", de: "Dein Abo ist aktiv." },
    body: {
      en: (v) => [
        { type: "h", text: "You're on Pro 🎉" },
        { type: "p", text: `Thanks ${strong(v.name ?? "there")} — your Verxa Pro subscription is active. Priority models and premium support are unlocked.` },
        { type: "meta", rows: [row("Plan", v.planName), row("Started", v.timestamp)] },
        { type: "btn", label: "Open Verxa", href: `${APP_URL}/chat` },
      ],
    },
    vars: ["name", "email", "planName", "timestamp"],
  },
  {
    id: "billing-subscription-upgraded",
    name: "Subscription upgraded",
    description: "Plan moved up.",
    category: "billing",
    kind: "transactional",
    sender: "billing",
    subject: { en: "Your plan was upgraded to {{planName}}", de: "Dein Plan wurde auf {{planName}} erhöht" },
    preheader: { en: "New limits apply immediately.", de: "Neue Limits gelten sofort." },
    body: {
      en: (v) => [
        { type: "h", text: `Upgraded to ${strong(v.planName ?? "Pro")}` },
        { type: "p", text: `${greeting(v)} your new limits apply immediately. Enjoy.` },
        subBtn,
      ],
    },
    vars: ["name", "email", "planName", "timestamp"],
  },
  {
    id: "billing-subscription-downgraded",
    name: "Subscription downgraded",
    description: "Plan moved down.",
    category: "billing",
    kind: "transactional",
    sender: "billing",
    subject: { en: "Your plan was changed to {{planName}}", de: "Dein Plan wurde auf {{planName}} geändert" },
    preheader: { en: "What changes for you.", de: "Was sich für dich ändert." },
    body: {
      en: (v) => [
        { type: "h", text: `Now on ${strong(v.planName ?? "")}` },
        { type: "p", text: `${greeting(v)} your plan was changed. The new limits apply from the next billing period.` },
        subBtn,
      ],
    },
    vars: ["name", "email", "planName", "timestamp"],
  },
  {
    id: "billing-subscription-cancelled",
    name: "Subscription cancelled",
    description: "Cancellation with access-until notice.",
    category: "billing",
    kind: "transactional",
    sender: "billing",
    subject: { en: "Your Verxa subscription was cancelled", de: "Dein Verxa-Abo wurde gekündigt" },
    preheader: { en: "Access continues until period end.", de: "Zugang bleibt bis Periodenende." },
    body: {
      en: (v) => [
        { type: "h", text: "Subscription cancelled" },
        { type: "p", text: `${greeting(v)} your subscription has been cancelled${v.note ? ` — ${strong(v.note)}` : ""}. You keep access until the end of the current period.` },
        subBtn,
      ],
    },
    vars: ["name", "email", "planName", "note", "timestamp"],
  },
  {
    id: "billing-payment-success",
    name: "Payment successful",
    description: "Receipt for a charge.",
    category: "billing",
    kind: "transactional",
    sender: "billing",
    subject: { en: "Payment received — thank you", de: "Zahlung erhalten — danke" },
    preheader: { en: "Your receipt is inside.", de: "Deine Quittung ist dabei." },
    body: {
      en: (v) => [
        { type: "h", text: "Payment successful ✓" },
        { type: "p", text: `${greeting(v)} we received your payment. Details below.` },
        { type: "meta", rows: [row("Amount", `${v.amount ?? ""} ${v.currency ?? ""}`.trim()), row("Plan", v.planName), row("When", v.timestamp)] },
        ...(v.invoiceUrl ? [{ type: "btn" as const, label: "View invoice", href: String(v.invoiceUrl) }] : []),
      ],
    },
    vars: ["name", "email", "amount", "currency", "planName", "invoiceUrl", "timestamp"],
  },
  {
    id: "billing-payment-failed",
    name: "Payment failed",
    description: "Action-required dunning.",
    category: "billing",
    kind: "transactional",
    sender: "billing",
    subject: { en: "Action needed: payment failed", de: "Handeln erforderlich: Zahlung fehlgeschlagen" },
    preheader: { en: "Please update your payment method.", de: "Bitte aktualisiere deine Zahlungsmethode." },
    body: {
      en: (v) => [
        { type: "h", text: "Payment failed" },
        { type: "p", text: `${greeting(v)} we couldn't charge your payment method for Verxa Pro.` },
        ...(v.note ? [{ type: "box" as const, text: String(v.note) }] : []),
        { type: "btn", label: "Update payment method", href: `${APP_URL}/account/subscription` },
      ],
    },
    vars: ["name", "email", "amount", "currency", "note"],
  },
  {
    id: "billing-payment-method-updated",
    name: "Payment method updated",
    description: "New card/SEPA stored.",
    category: "billing",
    kind: "transactional",
    sender: "billing",
    subject: { en: "Your payment method was updated", de: "Deine Zahlungsmethode wurde aktualisiert" },
    preheader: { en: "Future charges use the new method.", de: "Künftige Abbuchungen nutzen die neue Methode." },
    body: {
      en: (v) => [
        { type: "h", text: "Payment method updated" },
        { type: "p", text: `${greeting(v)} your payment method was updated. Future charges will use it.` },
        { type: "note", text: "Wasn't you? Contact support immediately." },
      ],
    },
    vars: ["name", "email", "timestamp"],
  },
  {
    id: "billing-invoice-available",
    name: "Invoice available",
    description: "New invoice ready.",
    category: "billing",
    kind: "transactional",
    sender: "billing",
    subject: { en: "Your Verxa invoice is ready", de: "Deine Verxa-Rechnung ist bereit" },
    preheader: { en: "Download it from your account.", de: "Lade sie in deinem Konto herunter." },
    body: {
      en: (v) => [
        { type: "h", text: "Invoice ready" },
        { type: "meta", rows: [row("Amount", `${v.amount ?? ""} ${v.currency ?? ""}`.trim()), row("Period", v.timestamp)] },
        ...(v.invoiceUrl ? [{ type: "btn" as const, label: "View invoice", href: String(v.invoiceUrl) }] : []),
      ],
    },
    vars: ["name", "email", "amount", "currency", "invoiceUrl", "timestamp"],
  },
  {
    id: "billing-invoice-reminder",
    name: "Invoice payment reminder",
    description: "Overdue/open invoice nudge.",
    category: "billing",
    kind: "transactional",
    sender: "billing",
    subject: { en: "Reminder: invoice {{amount}} {{currency}} is due", de: "Erinnerung: Rechnung fällig" },
    preheader: { en: "Please settle your invoice.", de: "Bitte begleiche deine Rechnung." },
    body: {
      en: (v) => [
        { type: "h", text: "Payment reminder" },
        { type: "p", text: `${greeting(v)} invoice of ${strong(`${v.amount ?? ""} ${v.currency ?? ""}`.trim())} is still open.` },
        ...(v.invoiceUrl ? [{ type: "btn" as const, label: "Pay now", href: String(v.invoiceUrl) }] : [subBtn]),
      ],
    },
    vars: ["name", "email", "amount", "currency", "invoiceUrl"],
  },
  {
    id: "billing-usage-warning",
    name: "Usage limit approaching",
    description: "80%+ of plan quota used.",
    category: "billing",
    kind: "transactional",
    sender: "billing",
    subject: { en: "You're nearing your Verxa usage limit", de: "Du näherst dich deinem Nutzungslimit" },
    preheader: { en: "Consider upgrading to avoid interruption.", de: "Erwäge ein Upgrade." },
    body: {
      en: (v) => [
        { type: "h", text: "Usage at 80%+" },
        { type: "p", text: `${greeting(v)} you've used most of your ${strong(v.planName ?? "current")} quota. Upgrade anytime to keep going without interruption.` },
        subBtn,
      ],
    },
    vars: ["name", "email", "planName", "amount"],
  },
  {
    id: "billing-usage-limit-reached",
    name: "Usage limit reached",
    description: "Quota exhausted.",
    category: "billing",
    kind: "transactional",
    sender: "billing",
    subject: { en: "You've reached your usage limit", de: "Du hast dein Nutzungslimit erreicht" },
    preheader: { en: "Upgrade to continue without limits.", de: "Upgrade für unbegrenzte Nutzung." },
    body: {
      en: (v) => [
        { type: "h", text: "Limit reached" },
        { type: "p", text: `${greeting(v)} you've used up your ${strong(v.planName ?? "current")} quota. It resets next period — or upgrade now for more.` },
        subBtn,
      ],
    },
    vars: ["name", "email", "planName"],
  },
  {
    id: "billing-renewal-reminder",
    name: "Plan renewal reminder",
    description: "Upcoming renewal notice.",
    category: "billing",
    kind: "transactional",
    sender: "billing",
    subject: { en: "Your Verxa plan renews soon", de: "Dein Verxa-Plan verlängert sich bald" },
    preheader: { en: "No action needed unless you want changes.", de: "Nichts zu tun, außer du willst ändern." },
    body: {
      en: (v) => [
        { type: "h", text: "Renewal coming up" },
        { type: "p", text: `${greeting(v)} your ${strong(v.planName ?? "Pro")} plan renews on ${strong(v.timestamp ?? "")}. No action needed.` },
        subBtn,
      ],
    },
    vars: ["name", "email", "planName", "timestamp", "amount", "currency"],
  },
  {
    id: "billing-trial-started",
    name: "Trial started",
    description: "Trial welcome.",
    category: "billing",
    kind: "transactional",
    sender: "billing",
    subject: { en: "Your Verxa trial started", de: "Deine Verxa-Testphase hat begonnen" },
    preheader: { en: "Enjoy everything, on us.", de: "Alles testen, auf uns." },
    body: {
      en: (v) => [
        { type: "h", text: "Trial started 🎉" },
        { type: "p", text: `${greeting(v)} your ${strong(v.planName ?? "Pro")} trial is active until ${strong(v.timestamp ?? "")}. No charge until then.` },
        { type: "btn", label: "Open Verxa", href: `${APP_URL}/chat` },
      ],
    },
    vars: ["name", "email", "planName", "timestamp"],
  },
  {
    id: "billing-trial-ending",
    name: "Trial ending soon",
    description: "Trial expiry nudge.",
    category: "billing",
    kind: "transactional",
    sender: "billing",
    subject: { en: "Your trial ends soon", de: "Deine Testphase endet bald" },
    preheader: { en: "Keep Pro without interruption.", de: "Pro ohne Unterbrechung behalten." },
    body: {
      en: (v) => [
        { type: "h", text: "Trial ending" },
        { type: "p", text: `${greeting(v)} your trial ends on ${strong(v.timestamp ?? "")}. Stay on Pro to keep everything.` },
        subBtn,
      ],
    },
    vars: ["name", "email", "planName", "timestamp"],
  },
  {
    id: "billing-trial-ended",
    name: "Trial ended",
    description: "Trial over, free plan continues.",
    category: "billing",
    kind: "transactional",
    sender: "billing",
    subject: { en: "Your trial ended — you're on Free", de: "Testphase beendet — du bist auf Free" },
    preheader: { en: "Upgrade anytime to get Pro back.", de: "Jederzeit wieder upgraden." },
    body: {
      en: (v) => [
        { type: "h", text: "Back on Free" },
        { type: "p", text: `${greeting(v)} your trial ended. You're on the Free plan now — upgrade anytime to get Pro back.` },
        subBtn,
      ],
    },
    vars: ["name", "email", "planName"],
  },
];
