/** Product + lifecycle templates. */
import { APP_URL } from "../config";
import { greeting, row, strong, type TemplateDef } from "./types";

const appBtn = { type: "btn" as const, label: "Open Verxa", href: `${APP_URL}/chat` };

export const PRODUCT_TEMPLATES: TemplateDef[] = [
  {
    id: "product-welcome",
    name: "Welcome to Verxa",
    description: "Post-verification onboarding email.",
    category: "product",
    kind: "transactional",
    sender: "hello",
    subject: { en: "You're verified — welcome to Verxa 🎉", de: "Verifiziert — willkommen bei Verxa 🎉" },
    preheader: { en: "Here's how to get the most out of Verxa.", de: "So holst du das Beste aus Verxa." },
    body: {
      en: (v) => [
        { type: "h", text: `You're in, ${strong(v.name ?? "there")}` },
        { type: "p", text: `${greeting(v)} your email is confirmed. Three things worth trying first:` },
        {
          type: "box",
          text: "1. Ask anything — pick a model at the bottom of the chat page.<br>2. Try an image or video from the composer.<br>3. Mention @Flyvia to search real flights.",
        },
        appBtn,
      ],
    },
    vars: ["name", "email"],
  },
  {
    id: "product-first-chat",
    name: "First chat started",
    description: "Celebrate the first conversation.",
    category: "product",
    kind: "transactional",
    sender: "hello",
    subject: { en: "Nice — your first Verxa chat ✦", de: "Dein erster Verxa-Chat ✦" },
    preheader: { en: "Here's what else Verxa can do.", de: "Was Verxa sonst noch kann." },
    body: {
      en: (v) => [
        { type: "h", text: "First chat done" },
        { type: "p", text: `${greeting(v)} you just had your first Verxa conversation. A few ideas for the next one:` },
        {
          type: "box",
          text: "• Summarize a long article with web search on.<br>• Generate a cinematic image.<br>• Plan a trip with @Flyvia.",
        },
        appBtn,
      ],
    },
    vars: ["name", "email"],
  },
  {
    id: "product-project-created",
    name: "Project created",
    description: "Confirm a new project.",
    category: "product",
    kind: "transactional",
    sender: "notifications",
    subject: { en: "Project created: {{projectName}}", de: "Projekt erstellt: {{projectName}}" },
    preheader: { en: "Your new project is ready.", de: "Dein neues Projekt ist bereit." },
    body: {
      en: (v) => [
        { type: "h", text: `Project ${strong(v.projectName ?? "")} is ready` },
        { type: "p", text: `${greeting(v)} your new project is set up. Chats, files and settings inside it stay organized in one place.` },
        { type: "btn", label: "Open project", href: `${APP_URL}/projects` },
      ],
    },
    vars: ["name", "email", "projectName"],
  },
  {
    id: "product-project-shared",
    name: "Project shared",
    description: "Someone shared a project with the recipient.",
    category: "product",
    kind: "transactional",
    sender: "notifications",
    subject: { en: "{{sharedBy}} shared a Verxa project with you", de: "{{sharedBy}} hat ein Projekt mit dir geteilt" },
    preheader: { en: "Take a look at what's inside.", de: "Schau dir an, was drin ist." },
    body: {
      en: (v) => [
        { type: "h", text: "A project was shared with you" },
        { type: "p", text: `${strong(v.sharedBy ?? "Someone")} shared ${strong(v.projectName ?? "a project")} with you on Verxa.` },
        { type: "btn", label: "View project", href: String(v.projectUrl ?? `${APP_URL}/projects`) },
      ],
    },
    vars: ["name", "email", "projectName", "sharedBy", "projectUrl"],
  },
  {
    id: "product-project-invitation",
    name: "Project invitation",
    description: "Invitation to collaborate, with accept link.",
    category: "product",
    kind: "transactional",
    sender: "notifications",
    subject: { en: "You're invited to collaborate on Verxa", de: "Einladung zur Zusammenarbeit bei Verxa" },
    preheader: { en: "Accept the invitation to join.", de: "Nimm die Einladung an." },
    body: {
      en: (v) => [
        { type: "h", text: "You're invited" },
        { type: "p", text: `${strong(v.sharedBy ?? "Someone")} invited you to collaborate on ${strong(v.projectName ?? "a Verxa project")}.` },
        { type: "btn", label: "Accept invitation", href: String(v.projectUrl ?? `${APP_URL}/projects`) },
        { type: "note", text: "This invitation expires in 7 days." },
      ],
    },
    vars: ["name", "email", "projectName", "sharedBy", "projectUrl"],
  },
  {
    id: "product-plugin-connected",
    name: "Plugin connected",
    description: "A chat plugin was enabled.",
    category: "product",
    kind: "transactional",
    sender: "notifications",
    subject: { en: "Plugin connected: {{featureName}}", de: "Plugin verbunden: {{featureName}}" },
    preheader: { en: "Your new plugin is ready to use.", de: "Dein neues Plugin ist bereit." },
    body: {
      en: (v) => [
        { type: "h", text: `${strong(v.featureName ?? "Plugin")} connected` },
        { type: "p", text: `${greeting(v)} the plugin is now active in your chats. You can disable it anytime under Plugins.` },
        { type: "btn", label: "Manage plugins", href: `${APP_URL}/plugins` },
      ],
    },
    vars: ["name", "email", "featureName"],
  },
  {
    id: "product-plugin-disconnected",
    name: "Plugin disconnected",
    description: "A chat plugin was disabled.",
    category: "product",
    kind: "transactional",
    sender: "notifications",
    subject: { en: "Plugin disconnected: {{featureName}}", de: "Plugin getrennt: {{featureName}}" },
    preheader: { en: "The plugin is no longer active.", de: "Das Plugin ist nicht mehr aktiv." },
    body: {
      en: (v) => [
        { type: "h", text: `${strong(v.featureName ?? "Plugin")} disconnected` },
        { type: "p", text: `${greeting(v)} the plugin was disconnected and is no longer active in your chats.` },
      ],
    },
    vars: ["name", "email", "featureName"],
  },
  {
    id: "product-integration-connected",
    name: "Integration connected",
    description: "External account (Gmail/Calendar/Drive) connected.",
    category: "product",
    kind: "transactional",
    sender: "notifications",
    subject: { en: "Integration connected: {{featureName}}", de: "Integration verbunden: {{featureName}}" },
    preheader: { en: "Verxa can now work with your account.", de: "Verxa kann jetzt damit arbeiten." },
    body: {
      en: (v) => [
        { type: "h", text: `${strong(v.featureName ?? "Integration")} connected` },
        { type: "p", text: `${greeting(v)} Verxa can now use your connected account inside chats (e.g. summarize emails). Disconnect anytime in Connected Apps.` },
        { type: "btn", label: "Connected apps", href: `${APP_URL}/account/connected-apps` },
      ],
    },
    vars: ["name", "email", "featureName"],
  },
  {
    id: "product-integration-disconnected",
    name: "Integration disconnected",
    description: "External account disconnected, tokens revoked.",
    category: "product",
    kind: "transactional",
    sender: "notifications",
    subject: { en: "Integration disconnected: {{featureName}}", de: "Integration getrennt: {{featureName}}" },
    preheader: { en: "Access was revoked.", de: "Der Zugriff wurde entzogen." },
    body: {
      en: (v) => [
        { type: "h", text: `${strong(v.featureName ?? "Integration")} disconnected` },
        { type: "p", text: `${greeting(v)} the integration was disconnected and its access tokens were revoked. Verxa can no longer read that account.` },
      ],
    },
    vars: ["name", "email", "featureName"],
  },
  {
    id: "product-important-notice",
    name: "Important product notification",
    description: "Must-read product notice (transactional).",
    category: "product",
    kind: "transactional",
    sender: "notifications",
    subject: { en: "Important: {{featureName}}", de: "Wichtig: {{featureName}}" },
    preheader: { en: "Please read — this affects your Verxa usage.", de: "Bitte lesen — betrifft deine Nutzung." },
    body: {
      en: (v) => [
        { type: "h", text: String(v.featureName ?? "Important notice") },
        ...(v.message ? [{ type: "box" as const, text: String(v.message) }] : []),
        appBtn,
      ],
    },
    vars: ["name", "email", "featureName", "message"],
  },
  {
    id: "product-system-notification",
    name: "System notification",
    description: "Generic system event notice.",
    category: "product",
    kind: "transactional",
    sender: "notifications",
    subject: { en: "Verxa system notification", de: "Verxa-Systemmitteilung" },
    preheader: { en: "Something changed in your workspace.", de: "Etwas hat sich geändert." },
    body: {
      en: (v) => [
        { type: "h", text: "System notification" },
        { type: "p", text: greeting(v) },
        ...(v.message ? [{ type: "box" as const, text: String(v.message) }] : []),
      ],
    },
    vars: ["name", "email", "message"],
  },
  {
    id: "product-feature-announcement",
    name: "Feature announcement",
    description: "Optional feature news (consent-gated).",
    category: "product",
    kind: "marketing",
    sender: "updates",
    subject: { en: "New in Verxa: {{featureName}}", de: "Neu bei Verxa: {{featureName}}" },
    preheader: { en: "Try it today in one click.", de: "Heute mit einem Klick testen." },
    body: {
      en: (v) => [
        { type: "h", text: `New: ${strong(v.featureName ?? "")}` },
        ...(v.message ? [{ type: "p" as const, text: String(v.message) }] : []),
        appBtn,
      ],
    },
    vars: ["name", "email", "featureName", "message"],
  },
  {
    id: "product-new-feature",
    name: "New feature available",
    description: "Short availability ping (consent-gated).",
    category: "product",
    kind: "marketing",
    sender: "updates",
    subject: { en: "{{featureName}} is now available", de: "{{featureName}} ist jetzt verfügbar" },
    preheader: { en: "Check it out in your workspace.", de: "Schau es dir an." },
    body: {
      en: (v) => [
        { type: "h", text: `${strong(v.featureName ?? "Something new")} is live` },
        { type: "p", text: `${greeting(v)} it's available in your workspace right now.` },
        appBtn,
      ],
    },
    vars: ["name", "email", "featureName"],
  },
  {
    id: "product-maintenance",
    name: "Service maintenance notification",
    description: "Planned maintenance window.",
    category: "product",
    kind: "transactional",
    sender: "notifications",
    subject: { en: "Scheduled Verxa maintenance", de: "Geplante Verxa-Wartung" },
    preheader: { en: "Short downtime expected.", de: "Kurze Ausfallzeit erwartet." },
    body: {
      en: (v) => [
        { type: "h", text: "Maintenance window" },
        { type: "p", text: `${greeting(v)} Verxa will be briefly unavailable for planned maintenance.` },
        { type: "meta", rows: [row("When", v.timestamp), row("Expected duration", v.note)] },
        { type: "p", text: "Thanks for your patience — we'll be right back." },
      ],
    },
    vars: ["name", "email", "timestamp", "note"],
  },
  {
    id: "product-status",
    name: "Service status notification",
    description: "Incident / recovery status.",
    category: "product",
    kind: "transactional",
    sender: "notifications",
    subject: { en: "Verxa status update", de: "Verxa-Statusupdate" },
    preheader: { en: "Current service status.", de: "Aktueller Servicestatus." },
    body: {
      en: (v) => [
        { type: "h", text: "Status update" },
        { type: "p", text: greeting(v) },
        ...(v.message ? [{ type: "box" as const, text: String(v.message) }] : []),
      ],
    },
    vars: ["name", "email", "message"],
  },
];
